#index:
#    path: /
#    controller: App\Controller\DefaultController::index
api_login:
    path: /api/login

# EndPoint de déconection
api_logout:
    path: /api/logout
    methods: GET

# EndPoint Refresh token
gesdinet_jwt_refresh_token:
    path: /api/token/refresh
    controller: gesdinet.jwtrefreshtoken::refresh
